version: '3.8'

services:
  mongodb:
    image: mongo:8.0.3
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend-cont:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-img
    container_name: backend-cont
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydb
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend-cont:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend-img
    container_name: frontend-cont
    ports:
      - "3000:3000"
    depends_on:
      - backend-cont
    

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
